steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/cloud-build-demo-230104/my-image2', '.']
tags: ['mytag1', 'mytag2']
images: ['gcr.io/cloud-build-demo-230104/my-image2']

 #- name: 'gcr.io/cloud-builders/docker'
  # args: ['push', 'gcr.io/cloud-build-demo-230104/my-image1']

