steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/abc', '.']
   env:
    - 'abc=my-image3'
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image4', '.'] 
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/abc']
   env:
    - 'abc=my-image3'

options:
    machineType: 'N1_HIGHCPU_8'


#tags: ['mytag1', 'mytag2']
#images: ['gcr.io/cloud-build-demo-230104/my-image3','gcr.io/cloud-build-demo-230104/my-image4']

 #- name: 'gcr.io/cloud-builders/docker'
  # args: ['push', 'gcr.io/cloud-build-demo-230104/my-image1']

 
